version: "3"

services:

  postgres-tests:
    image: postgres
    domainname: postgres-tests
    ports:
      - "5432:5432"
    volumes:
      - "./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh"
    environment:
      FORUM_DATABASE: simple_forum
      FORUM_USER: forum_admin
      FORUM_PASSWORD: forum_admin
