version: "3"

services:

  test-app:
    image: simple-forum
    command: >
      bash -c "
        alembic --config /opt/simple_forum/conf/alembic_test.ini upgrade head &&
        python -m pytest -vvv
      "
    env_file:
      - './conf/.test_env'

  test-forum-db:
    image: postgres
    container_name: test-forum-db
    volumes:
      - "./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh"
    env_file:
      - "./conf/.test_env"
