version: "3"

services:

  app:
    image: simple-forum
    command: >
      bash -c "
        alembic --config /opt/simple_forum/conf/alembic_dev.ini upgrade head &&
        python main.py
      "
    env_file:
      - './conf/.test_env'
    ports:
      - "8080:80"
    restart: always
    environment:
      DATABASE_HOST: "forum-db"

  forum-db:
    image: postgres
    container_name: forum-db
    volumes:
      - "./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh"
    env_file:
      - "./conf/.test_env"