#!/bin/sh -e

psql --variable=ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE $FORUM_DATABASE ENCODING 'UTF-8'
  LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8'
  TEMPLATE template0;
EOSQL

psql --variable=ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $FORUM_USER WITH PASSWORD '$FORUM_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $FORUM_DATABASE TO $FORUM_USER;
EOSQL
