server:
  host: 0.0.0.0
  port: 8080
  reuse_address: true
  reuse_port: true


database:
  host: 127.0.0.1
  port: 5435
  database: simple_forum
  user: forum_admin
  password: forum_admin

logging:
  version: 1
  formatters:
    console:
      format: "[%(asctime)s] %(name)s %(levelname)s %(message)s"
  handlers:
    console:
      level: DEBUG
      class: logging.StreamHandler
      formatter: console
  loggers:
    aiohttp:
      handlers: [console]
      level: DEBUG
      propagate: false
    simple_forum:
      handlers: [console]
      level: DEBUG
      propagate: false